// packages/components/layout/vue/src/Layout.tsx
import { defineComponent, computed, provide, reactive, onMounted, onUnmounted, type PropType, type ExtractPropTypes } from 'vue';
import { createResponsive, createStore, createStylesheet } from '@openlayout/core';
import type { LayoutConfig } from '@openlayout/config';
import type { ResponsiveState } from '@openlayout/core';

interface LayoutActions {
  toggleSidebar: () => void;
  setSidebarCollapsed: (value: boolean) => void;
  toggleHeader: () => void;
  setHeaderVisible: (value: boolean) => void;
  setHeaderFixed: (value: boolean) => void;
  toggleFooter: () => void;
  setFooterVisible: (value: boolean) => void;
  setFooterFixed: (value: boolean) => void;
}

const propTypes = {
  header: { type: Object as PropType<LayoutConfig['header']>, default: () => ({}) },
  footer: { type: Object as PropType<LayoutConfig['footer']>, default: () => ({}) },
  sidebar: { type: Object as PropType<LayoutConfig['sidebar']>, default: () => ({}) },
  content: { type: Object as PropType<LayoutConfig['content']>, default: () => ({}) },
  breakpoints: { type: Object as PropType<LayoutConfig['breakpoints']> },
  mobileBreakpoint: { type: Number, default: 768 },
  animation: { type: Object as PropType<LayoutConfig['animation']>, default: () => ({}) },
  className: { type: String, default: '' },
  style: { type: Object as PropType<Record<string, string | number>>, default: () => ({}) },
  onBreakpointChange: { type: Function as PropType<LayoutConfig['onBreakpointChange']> },
};

export type LayoutProps = ExtractPropTypes<typeof propTypes>;

export const Layout = defineComponent({
  name: 'ODLayout',
  props: propTypes,
  setup(props: LayoutProps) {
    const config = computed<LayoutConfig>(() => props as LayoutConfig);

    const responsive = computed<ResponsiveState>(() => createResponsive({
      breakpoints: props.breakpoints,
      mobileBreakpoint: props.mobileBreakpoint,
    }));

    const layoutState = createStore(config.value);
    const state = reactive(layoutState);

    const actions: LayoutActions = {
      toggleSidebar: () => { state.sidebar.collapsed = !state.sidebar.collapsed; },
      setSidebarCollapsed: (v: boolean) => { state.sidebar.collapsed = v; },
      toggleHeader: () => { state.header.visible = !state.header.visible; },
      setHeaderVisible: (v: boolean) => { state.header.visible = v; },
      setHeaderFixed: (v: boolean) => { state.header.fixed = v; },
      toggleFooter: () => { state.footer.visible = !state.footer.visible; },
      setFooterVisible: (v: boolean) => { state.footer.visible = v; },
      setFooterFixed: (v: boolean) => { state.footer.fixed = v; },
    };

    const styles = computed(() => createStylesheet(config.value, state, responsive.value, state.sidebar.collapsed));

    provide('layoutConfig', config);
    provide('layoutState', state);
    provide('layoutActions', actions);
    provide('layoutStyles', styles);
    provide('layoutResponsive', responsive);

    const updateResponsive = () => {
      const current = createResponsive({ breakpoints: props.breakpoints, mobileBreakpoint: props.mobileBreakpoint });
      props.onBreakpointChange?.(current.breakpoint, current.width);
    };

    onMounted(() => {
      if (typeof window !== 'undefined') {
        window.addEventListener('resize', updateResponsive);
        updateResponsive();
      }
    });

    onUnmounted(() => {
      if (typeof window !== 'undefined') {
        window.removeEventListener('resize', updateResponsive);
      }
    });

    return { styles, state };
  },
  render() {
    const { styles, $slots, className, style } = this;
    const rootClass = ['od-layout', className];

    return (
      <div class={rootClass} style={{ ...styles.root, ...style }}>
        {$slots.default?.()}
      </div>
    );
  },
});

// packages/components/layout/react/src/Layout.tsx
import React, { createContext, useContext, useState, useEffect, useMemo, type ReactNode } from 'react';
import { createResponsive, createLayoutState, createStylesheet } from '@openlayout/core';
import type { LayoutConfig, LayoutProps, Breakpoint } from '@openlayout/config';
import type { LayoutState, LayoutStyles, LayoutActions, ResponsiveState } from '@openlayout/core';

interface LayoutContextValue {
  config: LayoutConfig;
  state: LayoutState;
  styles: LayoutStyles;
  responsive: ResponsiveState;
  actions: LayoutActions;
}

const LayoutContext = createContext<LayoutContextValue | null>(null);

export { LayoutContext };

export const useLayout = () => {
  const context = useContext(LayoutContext);
  if (!context) {
    throw new Error('useLayout must be used within LayoutProvider');
  }
  return context;
};

interface LayoutComponentProps extends LayoutProps {
  children?: ReactNode;
}

export const Layout: React.FC<LayoutComponentProps> = (props) => {
  const { children, className, style, ...rest } = props;

  const config = useMemo<LayoutConfig>(() => rest as LayoutConfig, [rest]);

  const [, setTick] = useState(0);

  useEffect(() => {
    const updateResponsive = () => {
      setTick(t => t + 1);
      const current = createResponsive({ breakpoints: props.breakpoints, mobileBreakpoint: props.mobileBreakpoint });
      props.onBreakpointChange?.(current.breakpoint, current.width);
    };

    if (typeof window !== 'undefined') {
      window.addEventListener('resize', updateResponsive);
      updateResponsive();
    }

    return () => {
      if (typeof window !== 'undefined') {
        window.removeEventListener('resize', updateResponsive);
      }
    };
  }, [props.breakpoints, props.mobileBreakpoint, props.onBreakpointChange]);

  const responsive = useMemo<ResponsiveState>(() => createResponsive({
    breakpoints: config.breakpoints,
    mobileBreakpoint: config.mobileBreakpoint,
  }), [config.breakpoints, config.mobileBreakpoint, setTick]);

  const layoutState = useMemo(() => createLayoutState(config), [config]);

  const [sidebarCollapsed, setSidebarCollapsed] = useState(layoutState.sidebar.collapsed);
  const [headerVisible, setHeaderVisible] = useState(layoutState.header.visible);
  const [headerFixed, setHeaderFixed] = useState(layoutState.header.fixed);
  const [footerVisible, setFooterVisible] = useState(layoutState.footer.visible);
  const [footerFixed, setFooterFixed] = useState(layoutState.footer.fixed);

  const state = useMemo(() => ({
    ...layoutState,
    sidebar: { ...layoutState.sidebar, collapsed: sidebarCollapsed },
    header: { ...layoutState.header, visible: headerVisible, fixed: headerFixed },
    footer: { ...layoutState.footer, visible: footerVisible, fixed: footerFixed },
  }), [layoutState, sidebarCollapsed, headerVisible, headerFixed, footerVisible, footerFixed]);

  const actions: LayoutActions = useMemo(() => ({
    toggleSidebar: () => setSidebarCollapsed(prev => !prev),
    setSidebarCollapsed,
    toggleHeader: () => setHeaderVisible(prev => !prev),
    setHeaderVisible,
    setHeaderFixed,
    toggleFooter: () => setFooterVisible(prev => !prev),
    setFooterVisible,
    setFooterFixed,
  }), []);

  const responsive = useMemo<ResponsiveState>(() => createResponsive({
    breakpoints: config.breakpoints,
    mobileBreakpoint: config.mobileBreakpoint,
  }), [config.breakpoints, config.mobileBreakpoint]);

  const styles = useMemo(() => createStylesheet(config, state, responsive, sidebarCollapsed), [config, state, responsive, sidebarCollapsed]);

  const contextValue = useMemo(() => ({
    config,
    state,
    styles,
    responsive,
    actions,
  }), [config, state, styles, responsive, actions]);

  return (
    <LayoutContext.Provider value={contextValue}>
      <div className={`od-layout ${className ?? ''}`} style={{ ...styles.root, ...style }}>
        {children}
      </div>
    </LayoutContext.Provider>
  );
};
