// packages/components/layout/vue/src/Sidebar.tsx
import { computed, h, ref, watch, type VNodeChild } from 'vue';
import { useLayout } from './useLayout';
import type { SidebarProps } from '@openlayout/config';

export function Sidebar(props: SidebarProps) {
  const layout = useLayout();

  const isControlled = computed(() => props.collapsed !== undefined);

  const internalCollapsed = ref(props.defaultCollapsed ?? false);

  watch(() => props.defaultCollapsed, (newVal) => {
    internalCollapsed.value = newVal ?? false;
  });

  const collapsed = computed(() => {
    if (isControlled.value) {
      return props.collapsed ?? false;
    }
    return internalCollapsed.value;
  });

  const computedWidth = computed(() => {
    if (!props.visible) return 0;
    return collapsed.value
      ? (props.collapsedWidth ?? layout.collapsedWidth.value)
      : (props.width ?? layout.sidebarWidth.value);
  });

  const Tag = computed(() => props.as ?? 'aside');

  const handleToggle = () => {
    if (props.collapsible) {
      if (!isControlled.value) {
        internalCollapsed.value = !internalCollapsed.value;
      }
    }
  };

  const computedClass = computed(() => {
    const classes: string[] = ['layout-sidebar'];

    if (props.fullHeight) {
      classes.push('layout-sidebar-full-height');
    }

    if (collapsed.value) {
      classes.push('layout-sidebar-collapsed');
    }

    if (props.collapsible) {
      classes.push('layout-sidebar-collapsible');
    }

    if (layout.isMobile.value && props.overlay) {
      classes.push('layout-sidebar-overlay');
    }

    if (!props.visible) {
      classes.push('layout-sidebar-hidden');
    }

    if (props.className) {
      classes.push(props.className);
    }

    return classes;
  });

  const computedStyle = computed(() => {
    const style: Record<string, string | number | undefined> = {
      flexShrink: 0,
      width: computedWidth.value,
      transition: 'width 0.2s ease',
    };

    if (layout.isMobile.value && props.overlay) {
      style.position = 'fixed';
      style.top = 0;
      style.left = 0;
      style.bottom = 0;
      style.zIndex = 99;
    }

    if (props.fullHeight && !layout.isMobile.value) {
      style.height = '100%';
    }

    if (!props.visible) {
      style.overflow = 'hidden';
    }

    if (props.style) {
      Object.assign(style, props.style);
    }

    return style;
  });

  return () => h(Tag.value, {
    class: computedClass.value,
    style: computedStyle.value,
    onClick: handleToggle,
  }, props.children);
}

// packages/components/layout/react/src/Sidebar.tsx
import React, { useMemo, useState, useEffect, type ReactNode } from 'react';
import { useLayoutContext } from './useLayout';
import type { SidebarProps } from '@openlayout/config';

type ExtendedSidebarProps = SidebarProps & { 
  as?: keyof JSX.IntrinsicElements;
  children?: ReactNode;
};

export function Sidebar({
  as: Component = 'aside',
  className,
  style,
  children,
  collapsible,
  collapsed,
  defaultCollapsed = false,
  onCollapsedChange,
  fullHeight = true,
  overlay,
  width,
  collapsedWidth,
  visible = true,
}: ExtendedSidebarProps) {
  const { store, isMobile } = useLayoutContext();

  const isControlled = collapsed !== undefined;
  const [internalCollapsed, setInternalCollapsed] = useState(defaultCollapsed);

  useEffect(() => {
    setInternalCollapsed(defaultCollapsed);
  }, [defaultCollapsed]);

  const isCollapsed = isControlled ? collapsed : internalCollapsed;

  useEffect(() => {
    onCollapsedChange?.(isCollapsed);
  }, [isCollapsed, onCollapsedChange]);

  const computedWidth = useMemo(() => {
    return isCollapsed
      ? (collapsedWidth ?? store.collapsedWidth)
      : (width ?? store.sidebarWidth);
  }, [isCollapsed, collapsedWidth, store.collapsedWidth, width, store.sidebarWidth]);

  const classNames = useMemo(() => {
    const classes = ['layout-sidebar'];

    if (fullHeight) {
      classes.push('layout-sidebar-full-height');
    }

    if (isCollapsed) {
      classes.push('layout-sidebar-collapsed');
    }

    if (collapsible) {
      classes.push('layout-sidebar-collapsible');
    }

    if (isMobile && overlay) {
      classes.push('layout-sidebar-overlay');
    }

    if (!visible) {
      classes.push('layout-sidebar-hidden');
    }

    if (className) {
      classes.push(className);
    }

    return classes.join(' ');
  }, [fullHeight, isCollapsed, collapsible, isMobile, overlay, visible, className]);

  const computedStyle = useMemo(() => {
    const s: React.CSSProperties = {
      flexShrink: 0,
      width: visible ? computedWidth : 0,
      transition: 'width 0.2s ease',
    };

    if (isMobile && overlay) {
      s.position = 'fixed';
      s.top = 0;
      s.left = 0;
      s.bottom = 0;
      s.zIndex = 99;
    }

    if (fullHeight && !isMobile) {
      s.height = '100%';
    }

    if (!visible) {
      s.overflow = 'hidden';
    }

    if (style) {
      Object.assign(s, style);
    }

    return s;
  }, [computedWidth, isMobile, overlay, fullHeight, visible, style]);

  const handleToggle = () => {
    if (collapsible) {
      if (isControlled) {
        onCollapsedChange?.(!collapsed);
      } else {
        setInternalCollapsed(!internalCollapsed);
        onCollapsedChange?.(!internalCollapsed);
      }
    }
  };

  return (
    <Component 
      className={classNames} 
      style={computedStyle}
      onClick={collapsible ? handleToggle : undefined}
    >
      {children}
    </Component>
  );
}
