// packages/components/layout/react/src/Footer.tsx
import React, { useMemo, type ReactNode } from 'react';
import { useLayoutContext } from './useLayout';
import { LAYOUT_DEFAULTS, type FooterProps } from '@openlayout/config';

type ExtendedFooterProps = FooterProps & { 
  as?: keyof JSX.IntrinsicElements;
  children?: ReactNode;
};

export function Footer({ 
  as: Component = 'footer', 
  className, 
  style, 
  children, 
  height,
  fixed, 
  fullWidth 
}: ExtendedFooterProps) {
  const { store } = useLayoutContext();

  const classNames = useMemo(() => {
    const classes = ['layout-footer'];

    if (fixed ?? store.footerFixed) {
      classes.push('layout-footer-fixed');
    }

    if (fullWidth) {
      classes.push('layout-footer-full-width');
    }

    if (className) {
      classes.push(className);
    }

    return classes.join(' ');
  }, [store.footerFixed, fullWidth, className]);

  const computedStyle = useMemo(() => {
    const s: React.CSSProperties = { 
      flexShrink: 0,
      minHeight: height ?? store.footerHeight ?? LAYOUT_DEFAULTS.FOOTER_HEIGHT,
    };

    if (height) {
      s.height = height;
    }

    if (fixed ?? store.footerFixed) {
      s.position = 'fixed';
      s.bottom = 0;
      s.left = 0;
      s.right = 0;
      s.zIndex = 100;
    }

    if (style) {
      Object.assign(s, style);
    }

    return s;
  }, [height, store.footerHeight, fixed, store.footerFixed, style]);

  return (
    <Component className={classNames} style={computedStyle}>
      {children}
    </Component>
  );
}

// packages/components/layout/vue/src/Footer.tsx
import { computed, h } from 'vue';
import { useLayout } from './useLayout';
import { LAYOUT_DEFAULTS, type FooterProps } from '@openlayout/config';

type ExtendedFooterProps = FooterProps & {
  children?: import('vue').VNodeChild;
};

export function Footer(props: ExtendedFooterProps) {
  const layout = useLayout();

  const Tag = computed(() => props.as ?? 'footer');

  const computedClass = computed(() => {
    const classes: string[] = ['layout-footer'];

    if (props.fixed ?? layout.footerFixed.value) {
      classes.push('layout-footer-fixed');
    }

    if (props.fullWidth) {
      classes.push('layout-footer-full-width');
    }

    if (props.className) {
      classes.push(props.className);
    }

    return classes;
  });

  const computedStyle = computed(() => {
    const style: Record<string, string | number | undefined> = {
      flexShrink: 0,
    };

    const height = props.height ?? layout.footerHeight.value ?? LAYOUT_DEFAULTS.FOOTER_HEIGHT;
    style.minHeight = height;

    if (props.height) {
      style.height = props.height;
    }

    if (props.fixed ?? layout.footerFixed.value) {
      style.position = 'fixed';
      style.bottom = 0;
      style.left = 0;
      style.right = 0;
      style.zIndex = 100;
    }

    if (props.style) {
      Object.assign(style, props.style);
    }

    return style;
  });

  return () => h(Tag.value, { class: computedClass.value, style: computedStyle.value }, props.children);
}
