// packages/components/layout/react/src/Header.tsx
import React, { useMemo, type ReactNode } from 'react';
import { useLayoutContext } from './useLayout';
import { LAYOUT_DEFAULTS, type HeaderProps } from '@openlayout/config';

type ExtendedHeaderProps = HeaderProps & { 
  as?: keyof JSX.IntrinsicElements;
  children?: ReactNode;
};

export function Header({ 
  as: Component = 'header', 
  className, 
  style, 
  children, 
  height,
  fixed, 
  fullWidth 
}: ExtendedHeaderProps) {
  const { store } = useLayoutContext();

  const classNames = useMemo(() => {
    const classes = ['layout-header'];

    if (fixed ?? store.headerFixed) {
      classes.push('layout-header-fixed');
    }

    if (fullWidth) {
      classes.push('layout-header-full-width');
    }

    if (className) {
      classes.push(className);
    }

    return classes.join(' ');
  }, [store.headerFixed, fullWidth, className]);

  const computedStyle = useMemo(() => {
    const s: React.CSSProperties = { 
      flexShrink: 0,
      minHeight: height ?? store.headerHeight ?? LAYOUT_DEFAULTS.HEADER_HEIGHT,
    };

    if (height) {
      s.height = height;
    }

    if (fixed ?? store.headerFixed) {
      s.position = 'fixed';
      s.top = 0;
      s.left = 0;
      s.right = 0;
      s.zIndex = 100;
    }

    if (style) {
      Object.assign(s, style);
    }

    return s;
  }, [height, store.headerHeight, fixed, store.headerFixed, style]);

  return (
    <Component className={classNames} style={computedStyle}>
      {children}
    </Component>
  );
}

// packages/components/layout/vue/src/Header.vue
<template>
  <component :is="computedAs" :class="computedClass" :style="computedStyle">
    <slot />
  </component>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useLayout } from './useLayout';
import { LAYOUT_DEFAULTS, type HeaderProps } from '@openlayout/config';

const props = withDefaults(defineProps<HeaderProps>(), {
  as: 'header',
});

const layout = useLayout();

const computedAs = computed(() => props.as ?? 'header');

const computedClass = computed(() => {
  const classes: string[] = ['layout-header'];

  if (props.fixed ?? layout.headerFixed.value) {
    classes.push('layout-header-fixed');
  }

  if (props.fullWidth) {
    classes.push('layout-header-full-width');
  }

  if (props.className) {
    classes.push(props.className);
  }

  return classes;
});

const computedStyle = computed(() => {
  const style: Record<string, string | number> = {
    flexShrink: 0,
  };

  const height = props.height ?? layout.headerHeight.value ?? LAYOUT_DEFAULTS.HEADER_HEIGHT;
  style.minHeight = height;
  
  if (props.height) {
    style.height = props.height;
  }

  if (props.fixed ?? layout.headerFixed.value) {
    style.position = 'fixed';
    style.top = 0;
    style.left = 0;
    style.right = 0;
    style.zIndex = 100;
  }

  if (props.style) {
    Object.assign(style, props.style);
  }

  return style;
});
</script>

<style scoped>
.layout-header {
  flex-shrink: 0;
}

.layout-header-fixed {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 100;
}

.layout-header-full-width {
  width: 100%;
}
</style>
